package models.utils;

/**
 * Created by achy_ on 6/7/2017.
 */
public enum QuizTypeEnum {
    SINGLE_ANSWER, MULTIPLE_ANSWERS, INPUT_QUESTION, INPUT_QUESTION_TIMED,
    TIMED_SINGLE_ANSWER, TIMED_MULTIPLE_ANSWER, MULTIPLE_ANSWER_AND_INPUT,
    MULTIPLE_ANSWER_AND_INPUT_TIMED
}
